import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "lib")))

from db import add_word

# Paste your cleaned list below
cause_words = [
   "corrosion","erosion","abrasion","friction","fatigue","impact","vibration","overpressure","underpressure","surge","blockage","clogging","cavitation","turbulence","thermal_expansion","contraction","warping","swelling","melting","freezing","cracking","chipping","spalling","puncture","rupture","leakage","overflow","backflow","collapse","deformation","misalignment","detachment","slippage","overloading","loosening","wear","contamination","debris","obstruction","short_circuit","arc_fault","ground_fault","open_circuit","power_loss","voltage_spike",
"negligence","error","oversight","miscommunication","fatigue_error","improper_use","misuse","abuse","tampering","sabotage","theft","vandalism","distraction","inattention","overexertion","poor_training","lack_of_supervision","unauthorized_access","bypassing","delay","rushing","shortcutting","mishandling","mislabeling","misrouting","failure_to_inspect","skipped_step","incorrect_setting","improper_installation","faulty_repair","bad_wiring","loose_connection","unplugging","misconfiguration",
"humidity","condensation","flooding","leak_intrusion","water_damage","dust","dirt","mud","sand","salt_exposure","uv_exposure","ozone","oxidation","temperature_spike","heat_wave","cold_snap","freeze_thaw","wind_stress","hail_damage","lightning_strike","power_outage","brownout","surge_event","rodent_damage","insect_infestation","pest_activity","mold_growth","algae_bloom","chemical_spill","fuel_leak","seismic_activity","ground_shift","soil_movement","vibration_source","electromagnetic_interference","static_discharge",
"design_flaw","manufacturing_defect","supply_shortage","logistics_delay","inventory_error","software_bug","firmware_issue","miscalculation","sensor_fault","feedback_loop","config_drift","data_corruption","version_mismatch","timeout_event","clock_skew","unsynced_state","deadlock","race_condition","invalid_input","memory_leak","overheating","resource_starvation","failed_dependency","access_violation","expired_token","permissions_error","timeout","retry_loop","misfire","cascade_failure",
"overcurrent","undervoltage","overvoltage","overheating","thermal_runaway","capacitor_failure","fuse_blow","breaker_trip","overload_condition","inductive_kickback","power_fluctuation","phase_loss","phase_imbalance","resonance","transient_spike","impedance_mismatch","insulation_failure","arcing","sparking","wire_fatigue","conductor_break","coil_burnout","motor_lock","magnetic_interference",
"bacteria_growth","biofilm_buildup","algae_growth","mold_infestation","mildew_presence","fungal_colony","rot","decay","spoilage","fermentation","pest_infestation","vermin_activity","rodent_gnawing","corrosion_byproduct","acid_exposure","solvent_leak","gas_emission","oxidizer_contact","toxic_release","vapor_intrusion","reactive_mixture","chemical_reaction","catalyst_residue","resin_degradation",
"bacteria_growth","biofilm_buildup","algae_growth","mold_infestation","mildew_presence","fungal_colony","rot","decay","spoilage","fermentation","pest_infestation","vermin_activity","rodent_gnawing","corrosion_byproduct","acid_exposure","solvent_leak","gas_emission","oxidizer_contact","toxic_release","vapor_intrusion","reactive_mixture","chemical_reaction","catalyst_residue","resin_degradation",
"recursive_error","feedback_overload","runaway_process","latchup_condition","state_conflict","timing_violation","initialization_failure","buffer_overrun","stack_overflow","input_saturation","output_clipping","filter_blockage","checksum_mismatch","packet_loss","sync_failure","module_crash","timeout_expiry","retry_exhaustion","memory_corruption","null_reference","invalid_opcode","lockout_state","watchdog_trigger","system_halt",
"loose_mounting","improper_alignment","anchor_failure","seal_breach","gasket_shift","improper_torque","overtightening","tool_slip","calibration_error","orientation_error","connector_crossed","mismatched_thread","unsupported_load","floor_vibration","enclosure_damage","panel_warp","bracket_shift","rack_failure","unsecured_wire","grounding_error","routing_error","strain_relief_failure","installation_gap","drift_misalignment",
"unauthorized_access","credentials_leak","token_expiry","privilege_escalation","misconfigured_acl","broken_authentication","session_hijack","brute_force","phishing_attempt","malware_injection","software_exploit","zero_day","sql_injection","code_injection","buffer_injection","ransomware_trigger","virus_activity","trojan_payload","spyware_execution","password_reuse","exposed_port","unsecured_endpoint","cross_site_scripting","csrf_attack",
"foundation_settlement","soil_erosion","footing_crack","slab_shift","beam_deflection","column_buckle","wall_bulge","joint_separation","truss_failure","roof_sag","parapet_crack","anchor_pullout","masonry_spall","expansion_joint_shift","flashing_failure","grading_issue","water_intrusion","roof_load","lateral_force","uplift_pressure","drain_blockage","sewer_backup","waterproofing_failure","curtain_wall_shift",
"foundation_settlement","soil_erosion","footing_crack","slab_shift","beam_deflection","column_buckle","wall_bulge","joint_separation","truss_failure","roof_sag","parapet_crack","anchor_pullout","masonry_spall","expansion_joint_shift","flashing_failure","grading_issue","water_intrusion","roof_load","lateral_force","uplift_pressure","drain_blockage","sewer_backup","waterproofing_failure","curtain_wall_shift",
"earthquake_shock","flood_event","wildfire_damage","hurricane_force","tornado_touchdown","lightning_strike","hailstorm","landslide_event","volcanic_ash","tsunami_wave","snow_load","drought_condition","ice_dam","heat_dome","dust_storm","solar_flare","geomagnetic_disturbance","pollen_bloom","invasive_species","radiation_exposure","atmospheric_pressure_shift","ambient_noise","tidal_surge","barometric_drop",
"inadequate_training","lack_of_documentation","unclear_procedure","out_of_date_instruction","insufficient_oversight","maintenance_delay","poor_communication","interdepartmental_gap","failed_handoff","ambiguous_roles","staff_turnover","onboarding_gap","schedule_slip","manual_override","undocumented_change","stakeholder_dispute","incorrect_priority","change_request_backlog","weak_testing","no_red_team","missing_redundancy","poor_escalation","undefined_owner","knowledge_loss",
"material_fatigue","creep_failure","thermal_cycling","delamination","moisture_ingress","polymer_breakdown","uv_degradation","embrittlement","outgassing","phase_change","grain_growth","corrosion_fatigue","oxidation_layer","galvanic_reaction","thermal_stress","adhesive_failure","bond_breakage","paint_cracking","coating_peel","surface_scoring","resin_softening","ductility_loss","chalking","porosity_spread",
"packet_loss","latency_spike","jitter","connection_timeout","dns_failure","handshake_failure","routing_loop","ip_conflict","firewall_block","port_filtering","proxy_timeout","throttling","congestion_collapse","mtu_mismatch","packet_duplication","retransmission_limit","dropped_connection","ssl_error","certificate_expiry","dhcp_error","arp_conflict","nat_issue","socket_timeout","vlan_mismatch",
"void_in_cast","inclusion_defect","weld_crack","porosity_cluster","surface_void","mold_shift","delamination_layer","cooling_defect","overmolding_error","flashing","parting_line_shift","core_break","fiber_orientation_mismatch","tension_zone_crack","laminate_split","pressure_variation","resin_void","filler_contamination","uneven_thickness","extrusion_warp","profile_deviation","bad_batch","off_spec_mix","tolerance_violation",
"burnout","stress_response","distraction","multitasking","task_switching","misinterpretation","overconfidence","complacency","risk_tolerance","groupthink","peer_pressure","lack_of_awareness","fatigue_cycle","poor_judgment","attention_deficit","tunnel_vision","short_term_memory","hesitation","avoidance_behavior","misaligned_motivation","language_barrier","misalignment","interpersonal_conflict","disengagement",
"missing_input","delayed_output","false_positive","false_negative","invalid_state","undefined_behavior","fallback_trigger","backup_activation","incomplete_data","stale_data","missing_flag","mode_switch","silent_failure","logging_disabled","timeout_condition","blocked_path","stale_cache","dead_output","null_reference","orphaned_state","race_trigger","loop_escape","exception_thrown","recovery_timeout",
"signal_reflection","magnetization","charge_buildup","phase_shift","frequency_drift","resonance_peak","out_of_sync","grounding_loop","thermal_noise","sensor_drift","feedback_saturation","damping_loss","mechanical_hysteresis","lockup_state","wear_particle","oil_contamination","coolant_loss","gas_intrusion","vapor_lock","cavitation_event","inertial_force","harmonics_interference","unexpected_startup","watchdog_reset",
"checksum_error","metadata_loss","queue_overflow","buffer_starvation","dropped_packet","config_mismatch","invalid_token","update_failure","api_timeout","retry_storm","telemetry_gap","summ_bullshit",
 # ← truncate or continue your full list here
]

for word in cause_words:
    add_word("cause", word)

print(f"✅ Imported {len(cause_words)} causes.")
