import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "lib")))

from db import add_word

# Paste your cleaned list below
object_words = [
   "cinder_block","concrete_bag","rebar_cage","angle_iron","i_beam","steel_plate","plywood_sheet","osb_panel","drywall_panel","cement_board","backer_board","fiberboard_sheet","vapor_barrier_roll","house_wrap","insulation_batt","spray_foam_can","adhesive_tube","epoxy_kit","joint_compound_bucket","tile_thinset","grout_bag","sand_bag","gravel_sack","crushed_rock","topsoil_bag","mulch_bale","sod_roll","roofing_shingle","roofing_felt","roof_tile","ridge_vent","flashing_roll","metal_coil","wire_mesh","stucco_bucket","paint_can","stain_can","sealer_bottle","primer_gallon","caulk_tube","painter_tape_roll","brush_pack","roller_cover","roller_frame","paint_tray_liner","drop_cloth_roll",
"zipper_bag","poly_bag","mailer_bag","kraft_box","rigid_box","folding_carton","sleeve_box","clamshell_pack","blister_pack","shrink_wrap","hang_tag","price_tag","barcode_sticker","sku_label","tamper_seal","foil_pouch","desiccant_pouch","twist_tie","cable_tie","zip_seal","pull_tab","tear_strip","window_film","header_card","insert_card","backing_board","foam_inlay","cardboard_spacer","paper_wrap","padding_sheet","bubble_bag","stretch_film","banding_strap","corner_guard","pallet_strap","pallet_banding","label_sheet","label_roll","thermal_label","shipping_sticker","qr_label","barcode_tape","void_seal",
"pipette_tip","microtube_cap","centrifuge_strip","gel_combed","microarray_slide","blotting_sheet","reagent_strip","dilution_tube","sample_vial","reagent_reservoir","well_plate","plate_seal","slide_cover","immersion_oil","lab_wipe","test_strip","ph_strip","autoclave_bag","glove_pair","sharps_bag","spill_kit","bench_pad","foil_wrap","parafilm_roll","specimen_label","reaction_tube","enzyme_tube","buffer_bottle","tube_rack","absorbent_pad",
"button_widget","slider_bar","toggle_switch","radio_button","checkbox_field","text_input","password_input","date_picker","time_picker","drop_down","combo_box","modal_window","popup_panel","side_drawer","tab_bar","accordion_panel","stepper_control","nav_link","anchor_tag","progress_bar","loading_spinner","alert_box","toast_message","tooltip_bubble","icon_button","image_carousel","video_player","audio_player","seek_bar","scroll_track","pagination_dot","menu_item","context_menu","overlay_layer","focus_ring","cursor_icon","drag_handle","resizer_box","panel_frame",
"emergency_whistle","signal_flag","flare_gun","flare_rod","smoke_canister","strobe_light","hazard_triangle","road_flare","safety_cone","barrier_post","barricade_light","caution_sign","warning_banner","fire_alarm_box","pull_station","alarm_bell","exit_sign","glow_stick","emergency_ration","emergency_blanket","life_vest","lifebuoy_ring","throw_bag","tow_strap","tow_chain","jumper_cable","fuel_can","funnel_spout","reflective_tape","beacon_light","emergency_hammer","window_punch","seatbelt_cutter","dash_cam","first_aid_box","trauma_pack","oxygen_tank","regulator_knob",
"coin_roll","keychain_ring","button_cell","watch_battery","stamp_book","ticket_stub","matchbook","lighter_case","needle_threader","thimble_cap","glue_stick","eraser_tip","pencil_lead","ink_cartridge","razor_cartridge","nail_buffer","thread_spool","safety_pin","straight_pin","sewing_needle","measuring_tape","badge_holder","sunglass_case","eyeglass_cloth","microfiber_wipe","zipper_pull","drawstring_stop","cable_keeper","cord_wrap","bag_clip","binder_ring","index_card","sticky_tab","calendar_pad","push_pin_box","rubber_band_ball","cable_label","key_fob","usb_lanyard",
"rail_mount","track_plate","alignment_shim","locator_pin","indexing_plate","stop_block","corner_bracket","gusset_plate","linear_bearing","rotary_joint","cam_lever","lock_bar","set_ring","ratchet_wheel","detent_pin","cam_follower","bushing_block","rail_clamp","ball_transfer","leveling_mount","guide_rail","drag_chain","standoff_spacer","angle_clip","hinge_leaf","access_panel","knock_out","access_cover","cable_gland","thread_adapter","reducer_fitting","panel_cutout","snap_bushing","blind_plug",
"measuring_tape","caliper_gauge","digital_caliper","micrometer_screw","depth_gauge","feeler_strip","dial_indicator","bore_gauge","radius_gauge","thread_gauge","angle_finder","square_ruler","protractor_arc","contour_gauge","plumb_bob","line_level","laser_level","water_level","bubble_level","tape_reel","chalk_reel","paint_marker","marking_pencil","layout_knife","scribe_tool","datum_block","height_gauge","inspection_mirror","flashlight_pen","uv_light","laser_pointer","grid_paper",
"needle_case","thread_cutter","seam_ripper","stitch_marker","measuring_tape","pattern_weight","tracing_wheel","fabric_pen","quilting_ruler","rotary_cutter","cutting_mat","bobbin_case","bobbin_winder","presser_foot","feed_dog","thread_cone","serger_thread","tailor_chalk","darning_needle","thimble_ring","bias_tape","fabric_clip","hem_gauge","iron_rest","fusible_web","grommet_tool","rivet_setter","eyelet_punch","snap_button","snap_ring","upholstery_tack","batting_roll",
"power_cable","power_strip","plug_adapter","voltage_converter","extension_lead","power_brick","wall_charger","usb_adapter","cable_coupler","battery_pack","battery_case","battery_clip","fuse_cartridge","circuit_breaker","surge_protector","terminal_lug","bus_bar","terminal_ring","jumper_wire","binding_post","banana_plug","test_lead","wire_nut","wire_splitter","conduit_coupler","junction_cover","outlet_box","receptacle_face","power_inlet","rocker_switch","toggle_cover","grounding_screw",
"chalk_holder","bell_pull","service_bell","letter_opener","paperweight_block","magnifying_glass","cigar_cutter","match_striker","coat_toggle","boot_jack","shoehorn","hat_box","cane_tip","umbrella_cap","curtain_weight","carpet_tack","furniture_slider","door_chain","window_wedge","vent_register","sink_stop","drain_plug","chain_pull","toilet_roll","plunger_cup","bidet_nozzle","shower_ring","fan_blade","rotary_dial","clock_key","tv_remote","light_sensor","timer_switch",
    # ← truncate or continue your full list here
]

for word in object_words:
    add_word("object", word)

print(f"✅ Imported {len(object_words)} objects.")
